spring:
  application:
    name: pessoa
    version: "@project.version@"
  datasource:
    url: "@flyway.url@"
    username: "@flyway.user@"
    password: "@flyway.password@"
  flyway:
    enabled: false
    default-schema: "@flyway.schemas@"
  jpa:
    hibernate:
      ddl-auto: validate
server:
  servlet:
    context-path: /api

basePath: /api
